#ifndef __TINY_BURGER_CONFIG_H__
#define __TINY_BURGER_CONFIG_H__

#include <stdint.h>
#include "raylib.h"
#include "raymath.h"

#define TINY_BURGER

#define TINY_BURGER_DEBUG 1
#define TINY_BURGER_FPS 30

#define TINY_BURGER_TITLE "Tiny Burger"
#define TINY_BURGER_WIDTH 640
#define TINY_BURGER_HEIGHT 480

#define TINY_BURGER_MAP_WIDTH 17
#define TINY_BURGER_MAP_HEIGHT 12

#define TINY_BURGER_TILE 16

#define TINY_BURGER_FONT_COUNT 1
#define TINY_BURGER_TEXTURE_COUNT 1

#define TINY_BURGER_FONT_SIZE 24

#define TINY_BURGER_FONT_PATH_04B03 "data/fonts/04B_03__.TTF"
#define TINY_BURGER_TEXTURE_PATH_TILE "data/sprites/tiny_burger16.png"

#define TINY_BURGER_INTERPOLATION_MAX_VALUE 0.8f

#define TINY_BURGER_COLOR_0 0x28282eff
#define TINY_BURGER_COLOR_1 0x6c5671ff
#define TINY_BURGER_COLOR_2 0xd9c8bfff
#define TINY_BURGER_COLOR_3 0xf98284ff
#define TINY_BURGER_COLOR_4 0xb0a9e4ff
#define TINY_BURGER_COLOR_5 0xaccce4ff
#define TINY_BURGER_COLOR_6 0xb3e3daff
#define TINY_BURGER_COLOR_7 0xfeaae4ff
#define TINY_BURGER_COLOR_8 0x87a889ff
#define TINY_BURGER_COLOR_9 0xb0eb93ff
#define TINY_BURGER_COLOR_10 0xe9f59dff
#define TINY_BURGER_COLOR_11 0xffe6c6ff
#define TINY_BURGER_COLOR_12 0xdea38bff
#define TINY_BURGER_COLOR_13 0xffc384ff
#define TINY_BURGER_COLOR_14 0xfff7a0ff
#define TINY_BURGER_COLOR_15 0xfff7e4ff

#endif //__TINY_BURGER_CONFIG_H__